branch-defaults:
  default:
    environment: aswbeanPython27-dev
  master:
    environment: aswbeanPython27-dev
environment-defaults:
  aswbeanPython27-dev:
    branch: null
    repository: null
global:
  application_name: aswbeanPython27
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.5.2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
